#!/usr/bin/env bash
# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

# Update the package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Get the hostname of the server
hostname=$(hostname)

# Configure Nginx to add a custom header
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        add_header X-Served-By $hostname;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo service nginx restart
