#!/usr/bin/env bash
# Configuring load balancer with haproxy.

apt-get update
apt-get install -y haproxy

echo "frontend http
        bind *:80
        mode http
        default_backend backend-servers

backend backend-servers
        balance roundrobin
        mode http
        option forwardfor
        server 293002-web-01 52.72.14.223:80 check
        server 293002-web-02 3.95.32.236:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
