#!/usr/bin/env bash
# A script to Install and configure HAproxy on your lb-01 server
sudo apt-get -y update
sudo apt-get -y install haproxy
config=\
"backend yousif-backend
    balance roundrobin
    server 378634-web-01 18.206.207.38:80 check
    server 378634-web-02 3.86.7.50:80 check
    mode http
    timeout server 30s
    timeout connect 5s
frontend yousif-frontend
    bind *:80
    mode http
    default_backend yousif-backend
    timeout client 30s
"
echo "$config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
