#!/usr/bin/env bash
# 4 bad luck, 8 is your chance

i=0
while [ $i -lt 10 ]
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
